### ISSUE TITLE
v2.1 Short scenario, 1st Propaganda card bug

### ISSUE THREAD

**Issue by pwoloszun** [sellmerfud/coltwi#1]
Short Scenario
Bug: on my 1st Propaganda card(#67) your script entirely skipped:
- Support Phase
- Redeploy Phase
- Reset Phase

and then showed: 'Final Propaganda card' and 'Game Over: FLN wins!' - please take a look at attached screenshot.

PS. v1.5 worked fine
PPS. GREAT work and BIG THANK for your work
![Screenshot from 2019-06-01 11:21:01](https://user-images.githubusercontent.com/120793/58746612-550aaa80-8460-11e9-9a17-5ea71aeab211.png)

**Comment by pwoloszun** [comment]
Here is my save
[2019-06-01_short.zip](https://github.com/sellmerfud/coltwi/files/3243639/2019-06-01_short.zip)

**Comment by sellmerfud** [comment]
Piotr,
Thanks for reporting this.   It seems that I had added code for testing to force the program to consider the propaganda card to always be the final propaganda card.  I forgot to remove that after testing.
Sorry for the inconvenience.  Download version 2.2 and copy your saved game from 2.1.
Load the game and rollback to Turn #4 and you can pick up where you left off.
