### ISSUE TITLE
Card #2 - Balky Conscripts - was not able to take event as human

### ISSUE THREAD

**Issue by bsturk** [sellmerfud/coltwi#2]
Wanted to take the free train event, and it did not show up as an option, all I saw was:

Choose one:
----------------------------------------------------
1) Execute Limited Op
2) Pass

**Comment by sellmerfud** [comment]
Can you give me more information about the situation?  We you first to act on the card or did the FLN act first?
If the FLN acted first, what action did the FLN take?  Is it possible that the FLN took a limited action and prevented you from selecting the event?

I created a new game and selected `card 2` as the first card.  The FLN did a full action with special activity and then I was able to select the event.

**Comment by bsturk** [comment]
Sure thing, thanks for responding!

Here's what preceded my part of the turn, the FLN chose "Execute Op Only" which if I understand the rules should allow the GOV player to choose the event.

```
>>> Turn 10  (#2 Balky Conscripts) <<<
----------------------------------------------------
FLN is up (1st eligible, 10 resources)
Command (fln, pivot, or ?): fln

----------------------------------------------------
FLN chooses: Terror

FLN executes Terror operation: Oran
Decrease FLN resources by -1 to 9
Flip 1 Underground guerrilla to active in Oran
Add 1 terror marker to Oran
Remove Support marker from Oran
Move 'Support+Commit' marker to 22

FLN executes Terror operation: Philippeville
Decrease FLN resources by -1 to 8
Flip 1 Underground guerrilla to active in Philippeville
Add 1 terror marker to Philippeville
Remove Support marker from Philippeville
Move 'Support+Commit' marker to 20

FLN executes Terror operation: Souk Ahras
Decrease FLN resources by -1 to 7
Flip 1 Underground guerrilla to active in Souk Ahras
Add 1 terror marker to Souk Ahras
Remove Support marker from Souk Ahras
Move 'Support+Commit' marker to 18

Place the FLN eligibility cylinder in the Execute Op Only box

>>> Turn 10  (#2 Balky Conscripts) <<<
----------------------------------------------------
Government is up (2nd eligible, 27 resources)
Command (gov or ?): gov

Choose one:
----------------------------------------------------
1) Execute Limited Op
2) Pass
Selection: help
'help' is not valid. Must be one of:
1, 2, or abort action
Selection: 1
```

**Comment by sellmerfud** [comment]
If the first player chooses _Op Only_,  then the second player may only choose one of the actions adjacent to the _Op Only_ box in the initiative track.  The actions adjacent to _Op Only_ are: _Pass_ and _Execute Limited Op_.  

_Execute Event_ is not adjacent and so it is not an available action.

See the **Second Eligible** section of **Rule 2.3.2** on page 6 of the rulebook

**Comment by bsturk** [comment]
Oh wow, I didn't realize it had to be adjacent as well.  thank you!  sorry for the mis-report.
