### ISSUE TITLE
FLN - Napalm (Scorch the countryside) - card #35

### ISSUE THREAD

**Issue by richardmtl** [sellmerfud/coltwi#3]
The FLN bot has that capability, but the Assault spaces still cost only 2 resources for me.

```
List of capabilities:

Choose one:
----------------------------------------------------
1) Remove FLN:Napalm - Scorch the countryside
2) Remove FLN:Overkill - Revenge
3) Add Dual: Torture
4) Add FLN:Commandos - Zonal Commandos
5) Add FLN:Covert Movement - Cross Wilaya Coordination
6) Add FLN:SAS - Caution
7) Add FLN:Taleb Bomber - Effective
8) Add Gov:Commandos - Commandos de Chasse
9) Add Gov:Covert Movement - Dead Zones
10) Add Gov:Napalm - Effective
11) Add Gov:Overkill - Let God sort 'em out
12) Add Gov:SAS - Hearts & Minds
13) Add Gov:Taleb Bomber - Amateur
14) Finished
```
Assaults I just did (well, just one of them, to show the issue):
```
Government Assault operation
====================================================
spaces assaulted: OrleansVille, Philippeville, Sidi Bel Abbes

Choose one:
----------------------------------------------------
1) Select an assault space
2) Finished selecting assault spaces
3) Abort the entire Government turn
Selection: 1

Choose space to Assault:  Oran

Government executes Assault operation: Oran
Decrease Government resources by -2 to 14

Move the following pieces from Oran to AVAILABLE:
  1 Active guerrilla
```

I will Adjust my resources to compensate.

**Comment by sellmerfud** [comment]
I'll look into it.

Can you zip up your game directory and send it to me.  It is much faster
for me to reproduce the issue so that I don't have to  spend time
setting things up.

The game directory is in the 'games' subdirectory of where you installed
the software.
For example if you installed the software in ~/Downloads/fitl-0.23 and your
game is called test1, then the directory to zip up would be
~/Downloads/fitl-0.23/games/test1

Thanks.

**Comment by sellmerfud** [comment]
Sorry.  I just realized you are playing Colonial Twilight (not FitL)
So the directory would be something like:
~Download/coltwi-<vers>/games/test1

**Comment by sellmerfud** [comment]
I just set up an assault with the Napalm (Scorch) capability in play and
the assault decreased resources by 3.
If you send your saved game, I'll take a look and see what is going on.

**Comment by richardmtl** [comment]
[coltwi-issue-3.zip](https://github.com/sellmerfud/coltwi/files/10714728/coltwi-issue-3.zip)

Here you go!

**Comment by sellmerfud** [comment]
We now correctly decreases Gov resources by 3 for each Assault when the Napalm Scorch capability is in play.
