### ISSUE TITLE
Card #56 - typo

### ISSUE THREAD

**Issue by richardmtl** [sellmerfud/coltwi#4]
When I did Status - All I saw this:

Active Events
----------------------------------------------------
Pivotal     : none
Capabilities: FLN:Napalm - Scorch the countryside, FLN:Overkill - Revenge
Momentum    : Dual: Hardend Attitudes

`Hardend` should be `Hardened`

**Comment by sellmerfud** [comment]
Thanks.  Fixed for next version.
