### ISSUE TITLE
Version 2.13 won't run

### ISSUE THREAD

**Issue by febs** [sellmerfud/coltwi#9]
This happens on both Linux and Windows, except with slightly different error messages.

On Linux:

> Error: Unable to initialize main class coltwi.ColonialTwilight
> Caused by: java.lang.NoClassDefFoundError: scala/Option

On Windows:

> Exception in thread "main" java.lang.NoClassDefFoundError: scala/Option
>         at java.lang.Class.getDeclaredMethods0(Native Method)
>         at java.lang.Class.privateGetDeclaredMethods(Unknown Source)
>         at java.lang.Class.privateGetMethodRecursive(Unknown Source)
>         at java.lang.Class.getMethod0(Unknown Source)
>         at java.lang.Class.getMethod(Unknown Source)
>         at sun.launcher.LauncherHelper.validateMainClass(Unknown Source)
>         at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)
> Caused by: java.lang.ClassNotFoundException: scala.Option
>         at java.net.URLClassLoader.findClass(Unknown Source)
>         at java.lang.ClassLoader.loadClass(Unknown Source)
>         at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
>         at java.lang.ClassLoader.loadClass(Unknown Source)
>         ... 7 more
>

**Comment by febs** [comment]
btw it must obviously only be a build issue as the code runs with sbt. Thanks,

**Comment by sellmerfud** [comment]
I changed the build to use a newer version of Scala, but forgot to update the script to reference the newer libraries.
I now use a simple loader jar that handles this dynamically.
This was fixed in commit 55b3e6c
